name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CUDACXX: /usr/local/cuda/bin/nvcc

jobs:
  build: 
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Install python dependencies
      run: pip3 install numpy pytest pyquaternion
      
    - name: Install apt dependencies
      run: sudo apt install libeigen3-dev libboost-all-dev
      
    - name: Build from src
      run: mkdir build && cd build && cmake .. && make -j8
      
    - name: Make test
      run: cd build && make test
      
# test
