name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * 0

env:
  BUILD_TYPE: RelWithDebInfo # Use this build type to include code coverage
  CUDACXX: /usr/local/cuda/bin/nvcc

jobs:
  build: 
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: apt update
      run: apt update -y && apt upgrade -y
        
    - name: Build from src
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make -j8 && make install
      
    - name: Run tests # repeat because until-pass test 12 sporadically fails when using code coverage
      run: cd build && ctest -T Test --repeat until-pass:10 -T Coverage
      
    - name: Upload code coverage
      run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov
