name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * 0

env:
  BUILD_TYPE: Release # Use this build type to include code coverage
  CUDACXX: /usr/local/cuda/bin/nvcc

jobs:
  build: 
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Build from src
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make -j8 && make install
      
    - name: Run tests 
      run: cd build && ctest --output-on-failure

