name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CUDACXX: /usr/local/cuda/bin/nvcc

jobs:
  build: 
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: apt update
      run: apt update -y && apt upgrade -y
        
    - name: Build from src
      continue-on-error: true # The one test will most likely fail, but if we skip we lose a lot of coverage.
      run: mkdir build && cd build && cmake -DBUILD_COVERAGE=1 .. && make -j8 && make install
      
    - name: Run tests 
      run: cd build && ctest -T Test -T Coverage
      
    - name: Upload code coverage
      run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov

